const ADD_STUDENT = 'ADD_STUDENT';
const UPDATE_STUDENT = 'UPDATE_STUDENT';
const DELETE_STUDENT = 'DELETE_STUDENT';
const SET_SELECTED_STUDENT = 'SET_SELECTED_STUDENT';

export {
   ADD_STUDENT, UPDATE_STUDENT, DELETE_STUDENT, SET_SELECTED_STUDENT
}